### ISSUE TITLE
V2B02 Generative page "octave" parameter

### ISSUE THREAD

**Issue by 2b2a2t2** [midilab/aciduino#16]
octave parameter is not tweakable through buttons, works fine with knob but not with buttons
octaveS parameter works just fine

**Comment by midilab** [comment]
great to have a beta tester around! thanks for reporting! i hope you're enjoying jamming with aciduino.
fixed on:
https://github.com/midilab/aciduino/commit/68f9bedcb1fc44458008ba650fac2aff68767a72

Soon i will make a release as beta2, waiting a bit more bugs and new features to come, but you can clone the latest changes on the repo to use the fixes. remember to init submodules. check README.md

**Comment by 2b2a2t2** [comment]
Hello and thanks for this work !
I tested Beta 3 and have nothing to report, a small fix when exiting the tempo menu (left and right buttons only work after pressing up or down a second time)
For the jamming part, a few more CCs would be much appreciated in the 808 live page, it would be nice to add a few pots or encoders, the generate button is a delight.
