### ISSUE TITLE
Midi clock loss

### ISSUE THREAD

**Issue by 2b2a2t2** [midilab/aciduino#17]
Hello, 
using V2B03
I was able to reproduce the issue several times, using different pluggins, tweaking the resonance CC makes the aciduino crash, interface and sequencer are still running, controls are responding, but the DAW says the MIDI connection was lost, and my MIDI monitor does not receive information anymore from the aciduino.

**Comment by midilab** [comment]
Any code changes made for this beta3 from your side? like new mici CC or number of tracks?

Are you using teensy lc or 3.6?

thanks for test and reporting!

**Comment by 2b2a2t2** [comment]
using a Teensy 3.2, the only code changes I made are the button pins (had 2 pairs of buttons reversed)
I no longer have this issue since I uncommented the extra CC in the live page and re-upladed the sketch in the teensy

**Comment by midilab** [comment]
great! auto fix bugs!
the midi control object part has some flaws for extend that i intent to correct soon, i know it works on the beta but add or remove or creating another track without made some changes could lead to that freeze.

**Comment by midilab** [comment]
what are the new cc you are looking for? drums?

**Comment by 2b2a2t2** [comment]
in the 808 engine, one CC per voice would be great !
