### ISSUE TITLE
UONE presentation ?

### ISSUE THREAD

**Issue by 2b2a2t2** [midilab/aciduino#23]
What is this secret weapon that looks so attractive and that you display everywhere, are the PCB ready ? for sale somewhere ? can we create one of our own waiting for this to be available ? the code seems to imply multiplexing touch pins with a 4067, can we have some more details ? wiring diagram ? workflow ?

**Comment by midilab** [comment]
this is a new series of uModular modules using uCtrl, aciduino will be the first app for uModular project.
https://github.com/midilab/uMODULAR

I will release the schematic and boards for selling soon, just need to finish the review of the uOne + base module + pots module + cv/gate module.

The code is using captouch driver of uCtrl(not released yet), and you rigth, capacitive touch using the pcb cooper area and 2x 4067 for 32 buttons.
