### ISSUE TITLE
V2 Beta 05 Navigation issue

### ISSUE THREAD

**Issue by 2b2a2t2** [midilab/aciduino#25]
Hello,
 I'm having a strange behaviour on SEQR page 1 (left page), controls seem to be in the wrong order : 

tune    | transpose
- - - -
[°°°°[°°°°[°°°°[°°°°
lenght | shift

I also cannot switch from tune to transpose or from lenght to shift, previous and next buttons act like up and down, they are only efficient in the bar or sequence item

It's the same in both 303 and 808 engines.

**Comment by midilab** [comment]
its fixed on main branch, but not released as a beta yet, you can clone the repo and init him(init uCtrl and uClock libraries)

**Comment by 2b2a2t2** [comment]
Thanks ! Nice and quick !
