### ISSUE TITLE
Seqr Page V2Beta10

### ISSUE THREAD

**Issue by 2b2a2t2** [midilab/aciduino#29]
The second SEQR page when in a 808 engine is now a live play page ? I cannot move the select step box with arrows but I see the moving box, and pushing the on/off button for this step will only activate the step under the running box.
IT'S NOT A BUG IT'S A FEATURE !
this is actually simpler and quicker than navigating to the desired step, but a deletion would be a great implementation too !!

**Comment by midilab** [comment]
That is actually an old feature, maybe from beta7 i guess... the original TB303 and TR808 all has this function, a TAP, soh you can record in realtime by tapping, for 303 you can twist the pot to change note while TAPing like crazy to get some great sequences too, it records the note the POT is poiting at the time, if you hold the button you get a longer note with TIE on each step while holding. For the 808 tap just put a note at the time you tap. 

So for that function to be alive i need to sacrifice the other button that "deletes" but i made the other one as a switch state(press once, you put a note on selected, press again on a selected with note it deletes).

I really need sometime to write a proper manual with updates for new stuffs.

Other live focused feature like the TAP was the "last used midi control" on live page, once you get to you preffered control, you can change back to the mute page and use the control(change tracks wont change the pot either, he keeps the last used one for track and parameter).
