### ISSUE TITLE
Where is the audio output scheme?

### ISSUE THREAD

**Issue by Diodiodanm** [midilab/aciduino#35]
Where is the schematic audio output?

**Comment by midilab** [comment]
Aciduino is a step sequencer clone only, no audio output, only MIDI and CV/gate(on roadmap) outputs at this stage.

Maybe you can check this project wich has 2x tb303(synthesized clone) and 2x tr808(sampler), but no direct step sequencer feature like aciduino, but it has a acid like generator for phrases wich is quite nice:
https://github.com/copych/AcidBox

**Comment by Diodiodanm** [comment]
thanks for the answer, I'm new to midi controller. your answer is good for me define my initial project.
