### ISSUE TITLE
Audi out

### ISSUE THREAD

**Issue by Maitresinh** [midilab/aciduino#47]
Juste cannot see where it is...

**Comment by midilab** [comment]
Can you elaborate please?

**Comment by Maitresinh** [comment]
yes sorry. i mean i can't see any audio out, jack, RCA or anything else (nor a dac).
Am i missng something ?

**Comment by Maitresinh** [comment]
Or it's just a sequencer with no sounds ?

**Comment by midilab** [comment]
Its a multitrack sequencer only, no DSP or sounds.
